language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381903-3_Strashenko_lab5
  - make -j
  - ./test/MP5_TESTS
notifications:
  email: false